/* ===== EDIT ME: real business data ===== */
const BIZ={phone:"+918424853038",wa:"918424853038"};
const SOCIAL={INSTAGRAM_URL:"",FACEBOOK_URL:"",LINKEDIN_URL:""}; /* empty = hidden */
const SHOW_TESTIMONIALS=true; /* keep true only with genuine client feedback */
const IMG={hero:""}; /* optional URL / data URI */
/* ===== DEMO DATA (replace with verified listings; set img to your photo URL) ===== */
const LOCS=["Ghatkopar","Vikhroli","Bhandup","Andheri East","Andheri West","Thane"];
const PROPS=[
["AJMERA","Pant Nagar, Ghatkopar East","Ghatkopar","2 BHK Apartment","720 sq.ft.","₹1.85 Cr*","Modern residential living in a well-connected Mumbai neighbourhood with access to daily conveniences, transportation and key city locations.",["Lift","Covered Parking","24x7 Security"]],
["Serene Heights","Rajawadi Road, Ghatkopar West","Ghatkopar","2 BHK Apartment","690 sq.ft.","₹1.65 Cr*","A comfortable home close to the railway station, markets and schools, suited to families looking for everyday convenience.",["Lift","Power Backup","Security"]],
["Lakeview Residency","Vikhroli East","Vikhroli","1 BHK Apartment","430 sq.ft.","₹1.05 Cr*","A compact, well-planned apartment with easy access to the Eastern Express Highway and nearby business hubs.",["Lift","Parking","CCTV"]],
["Green Court","Bhandup West","Bhandup","2 BHK Apartment","640 sq.ft.","₹1.35 Cr*","Spacious living in a residential neighbourhood with good road and rail connectivity towards Thane and central Mumbai.",["Lift","Garden","Security"]],
["Metro Heights","Andheri East","Andheri East","2 BHK Apartment","710 sq.ft.","₹2.10 Cr*","A city apartment near metro and business districts, ideal for professionals who value a shorter commute.",["Lift","Parking","Gym"]],
["Seaside Residency","Andheri West","Andheri West","2 BHK Apartment","760 sq.ft.","₹2.85 Cr*","Well-located home in a lively western suburb with dining, shopping and transport close by.",["Lift","Covered Parking","Security"]],
].map((p,i)=>({id:i,name:p[0],loc:p[1],area:p[2],cfg:p[3],sz:p[4],price:p[5],desc:p[6],am:p[7],type:p[8]||"Residential",img:""}));
PROPS[0].img="images/property-1.jpg";
PROPS[1].img="images/property-2.jpg";
PROPS[2].img="images/property-3.jpg";
PROPS[3].img="images/property-5.jpg";
PROPS[4].img="images/property-4.jpg";
PROPS[2].name="Adityaraj";
const REDEV=["Ghatkopar","Ghatkopar West","Vikhroli","Bhandup","Thane"].map(n=>({t:n+" Redevelopment Opportunity",l:n==="Ghatkopar"?"Ghatkopar East":n,s:"Redevelopment Opportunity"}));
const LDESC={"Ghatkopar":"Our home base, with our office in Pant Nagar.","Vikhroli":"Eastern suburb along the corridor.","Bhandup":"Eastern suburb between Vikhroli and Thane.","Andheri East":"Western-side commercial and residential hub.","Andheri West":"Well-known western suburb locality.","Thane":"Key city at the northern end of our corridor."};
const TEST=[["Amit Shah","Ghatkopar East","Clear communication from the first call. Every site visit was well organised and my questions were answered patiently."],["Rahul Patil","Vikhroli","I felt the guidance matched what I actually needed, not what was easiest to sell. A professional experience."],["Sneha Mehta","Bhandup","Helpful, responsive and easy to reach. They understood our budget and shortlisted only relevant options."],["Nilesh Desai","Thane","Good understanding of the local market and honest advice during our property discussions."],["Pooja Kulkarni","Andheri East","Smooth coordination from enquiry to site visit. Friendly, professional and always available on WhatsApp."]];
const DOCS=[]; /* genuine documents only: {title:"",issuer:"",img:"URL or data URI"} */
/* ===================================== */
const P={wa:'<path d="M3 21l1.6-4.7A8.5 8.5 0 1 1 8 19.6z"/><path d="M9 9.5c0 3 2.5 5.5 5.5 5.5l1-1.5-2-1-1 .7a4 4 0 0 1-1.7-1.7l.7-1-1-2z"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',pin:'<path d="M12 21s7-6 7-11a7 7 0 0 0-14 0c0 5 7 11 7 11z"/><circle cx="12" cy="10" r="2.5"/>',ck:'<path d="M20 6L9 17l-5-5"/>',ph:'<path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z"/>',ml:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 7l9 6 9-6"/>',key:'<circle cx="8" cy="15" r="4"/><path d="M11 12l9-9M16 7l3 3"/>',tag:'<path d="M3 12V3h9l9 9-9 9z"/><circle cx="7.5" cy="7.5" r="1.5"/>',cmp:'<circle cx="12" cy="12" r="9"/><path d="M15.5 8.5l-2 5-5 2 2-5z"/>',bld:'<rect x="5" y="3" width="14" height="18" rx="1"/><path d="M9 7h2M13 7h2M9 11h2M13 11h2M10 21v-4h4v4"/>',shop:'<path d="M4 9l1-5h14l1 5M4 9a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 4 0M5 12v8h14v-8"/>',inv:'<path d="M3 17l6-6 4 4 8-8M15 7h6v6"/>',eye:'<circle cx="12" cy="12" r="3"/><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z"/>',sh:'<path d="M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z"/>',us:'<circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M16 5a3 3 0 0 1 0 6M21 20a5 5 0 0 0-4-5"/>',hs:'<path d="M20 7l-9 9-4-4M4 12v7h16"/>',hd:'<path d="M12 21s-8-5-8-11a5 5 0 0 1 8-3 5 5 0 0 1 8 3c0 6-8 11-8 11z"/>',ig:'<rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/>',fb:'<path d="M14 8h3V4h-3a4 4 0 0 0-4 4v3H7v4h3v6h4v-6h3l1-4h-4V8z"/>',li:'<path d="M4 9h4v11H4zM6 4v1M11 9h4v2c1-2 3-2.5 5-2v11h-4v-6c0-2-3-2-3 0v6h-2z"/>'};
const ic=n=>`<svg class="i" viewBox="0 0 24 24" aria-hidden="true">${P[n]||""}</svg>`;
const $=id=>document.getElementById(id),wa=m=>`https://wa.me/${BIZ.wa}?text=${encodeURIComponent(m)}`;
const MSG={gen:"Hello B.H Akhade Real Estate, I would like to know more about your services.",prop:"Hello B.H Akhade Real Estate, I am interested in a property. Please share more details.",red:"Hello B.H Akhade Real Estate, I would like to discuss a redevelopment opportunity.",visit:"Hello B.H Akhade Real Estate, I would like to arrange a property site visit."};
function bld(i){const h=[205,185,215,170,195,225,160][i%7];let r="";for(let k=0;k<7;k++){const x=20+k*54,y=70+((k*37+i*23)%70);r+=`<rect x="${x}" y="${y}" width="42" height="${240-y}" fill="hsl(${h},30%,${22+k%3*5}%)"/>`;for(let j=0;j<4;j++)r+=`<rect x="${x+8}" y="${y+12+j*22}" width="8" height="10" fill="#C5A46D" opacity=".55"/><rect x="${x+24}" y="${y+12+j*22}" width="8" height="10" fill="#C5A46D" opacity=".3"/>`}return `<svg viewBox="0 0 400 240" preserveAspectRatio="xMidYMax slice" role="img" aria-label="Representative illustration"><rect width="400" height="240" fill="hsl(${h},35%,${60+i%3*4}%)"/>${r}</svg>`}
const imgOf=p=>p.img?`<img src="${p.img}" alt="${p.name}, ${p.loc}" loading="lazy" style="width:100%;height:100%;object-fit:cover">`:bld(p.id);
function link(){document.querySelectorAll('[data-wa]').forEach(a=>{a.href=wa(MSG[a.dataset.wa]||a.dataset.wa);a.target="_blank";a.rel="noopener"})}
function icons(){document.querySelectorAll('i[data-i]').forEach(e=>e.outerHTML=ic(e.dataset.i))}
$('svc').innerHTML=[["key","Property Buying","Explore residential and commercial property opportunities based on your preferred location, requirements and budget."],["tag","Property Selling","Receive personalized assistance in presenting your property and connecting with potential buyers."],["cmp","Real Estate Consultancy","Get practical guidance while exploring property options, comparing opportunities and planning your next move."],["bld","Redevelopment Consultancy","Consultation and coordination support for property owners and housing societies exploring redevelopment opportunities."],["shop","Commercial Property","Explore shops, offices and other commercial real estate opportunities across selected Mumbai locations."],["inv","Property Investment Consultancy","Discuss real estate opportunities based on your investment objectives, preferred location and budget."]].map(s=>`<div class="sv rv"><div class="ic">${ic(s[0])}</div><h3>${s[1]}</h3><p>${s[2]}</p><a class="ln" data-wa="Hello B.H Akhade Real Estate, I would like to enquire about ${s[1]}.">Enquire Now →</a></div>`).join("");
const EDIT=/edit/.test(location.hash+location.search);
try{const s=JSON.parse(localStorage.getItem('akhade-imgs')||'{}');PROPS.forEach(p=>{if(s[p.id])p.img=s[p.id]})}catch(e){}
function savePhoto(id,file){const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const k=Math.min(1,900/im.width),c=document.createElement('canvas');c.width=im.width*k;c.height=im.height*k;c.getContext('2d').drawImage(im,0,0,c.width,c.height);const u=c.toDataURL('image/jpeg',.8);PROPS[id].img=u;try{const s=JSON.parse(localStorage.getItem('akhade-imgs')||'{}');s[id]=u;localStorage.setItem('akhade-imgs',JSON.stringify(s))}catch(e){}draw()};im.src=r.result};r.readAsDataURL(file)}
let ft="All",fl="All";
$('ft').innerHTML=["All","Residential","Commercial","Redevelopment"].map(t=>`<button class="ch${t==="All"?" on":""}" data-t="${t}">${t}</button>`).join("");
$('fs').innerHTML=["All",...LOCS].map(l=>`<option value="${l}">${l==="All"?"All Locations":l}</option>`).join("");
function draw(){const L=PROPS.filter(p=>(ft==="All"||p.type===ft)&&(fl==="All"||p.area===fl));
$('props').innerHTML=L.length?L.map(p=>`<article class="pc rv v"><div class="im">${imgOf(p)}<span class="tg">${p.type}</span>${EDIT?`<label class="edt">${p.img?"Change":"Add"} photo<input type="file" accept="image/*" data-p="${p.id}" aria-label="Add photo for ${p.name}"></label>`:""}</div><div class="pb"><h3>${p.name}</h3><div class="lc">${p.loc}</div><div class="mt"><div><small>Configuration</small>${p.cfg}</div><div><small>Carpet Area</small>${p.sz}</div><div><small>Price</small>${p.price}</div><div><small>Property Type</small>${p.type}</div></div><p style="color:var(--mu);font-size:14px;margin-bottom:12px">${p.desc}</p><div class="chips" style="margin:0 0 16px">${p.am.map(a=>`<span>${a}</span>`).join("")}</div><div class="rw"><button class="btn g1" data-d="${p.id}">View Details</button><a class="btn wa" data-wa="Hello B.H Akhade Real Estate, I am interested in ${p.name}, ${p.loc}. Please share more details.">${ic('wa')}Enquire Now</a></div></div></article>`).join(""):`<div style="grid-column:1/-1;padding:30px;border:1px dashed var(--bd)">No listings in this category right now. <a class="ln" data-wa="prop">Enquire on WhatsApp →</a> for current opportunities.</div>`;link()}
$('ft').onclick=e=>{const b=e.target.closest('button');if(!b)return;ft=b.dataset.t;document.querySelectorAll('#ft .ch').forEach(x=>x.classList.toggle('on',x===b));draw()};
$('fs').onchange=e=>{fl=e.target.value;draw()};
$('props').addEventListener('change',e=>{const i=e.target.closest('input[data-p]');if(i&&i.files[0])savePhoto(+i.dataset.p,i.files[0])});
if(EDIT)$('props').insertAdjacentHTML('beforebegin','<div class="en"><b>Edit mode:</b> tap "Add photo" on any card to pick an image from your device. Photos are saved in this browser only. To show them to every visitor, put the image in the <code>img</code> field of PROPS.</div>');
const md=$('md');let last;
$('props').onclick=e=>{const b=e.target.closest('[data-d]');if(!b)return;const p=PROPS[b.dataset.d];last=b;$('mc').innerHTML=`<button class="x" id="cx" aria-label="Close">×</button><div class="im">${imgOf(p)}</div><div class="pb"><span class="tg" style="position:static;align-self:flex-start;margin-bottom:10px">${p.type}</span><h3 style="font-size:26px">${p.name}</h3><div class="lc">${p.loc}</div><div class="mt"><div><small>Configuration</small>${p.cfg}</div><div><small>Carpet Area</small>${p.sz}</div><div><small>Price</small>${p.price}</div></div><p style="color:var(--mu);font-size:14px;margin-bottom:12px">${p.desc}</p><div class="chips" style="margin:0 0 14px">${p.am.map(a=>`<span>${a}</span>`).join("")}</div><p style="font-size:12px;color:var(--mu);margin-bottom:14px">*Price indicative and subject to change. Please verify details before any transaction.</p><div class="rw"><a class="btn wa" data-wa="Hello B.H Akhade Real Estate, I am interested in ${p.name}, ${p.loc}. Please share more details.">${ic('wa')}WhatsApp</a><a class="btn t" href="tel:+918424853038">${ic('ph')}Call Now</a><a class="btn g1" href="mailto:akhadea431@gmail.com?subject=Enquiry: ${encodeURIComponent(p.name)}">${ic('ml')}Email</a></div></div>`;link();md.classList.add('on');$('cx').focus();$('cx').onclick=cl};
const cl=()=>{md.classList.remove('on');last&&last.focus()};md.onclick=e=>{if(e.target===md)cl()};document.addEventListener('keydown',e=>{if(e.key==="Escape")cl()});
$('rl').innerHTML=["Initial redevelopment discussion","Property-owner consultation","Housing society consultation","Developer communication","Opportunity exploration","Project information coordination","Site discussion coordination"].map(t=>`<li>${ic('ck')}${t}</li>`).join("");
$('rd').innerHTML=REDEV.map(r=>`<div class="rd rv"><span class="tg">${r.s}</span><h3>${r.t}</h3><p>${r.l}</p><a class="ln" style="color:#e2c896" data-wa="red">Discuss →</a></div>`).join("");
$('loc').innerHTML=LOCS.map((l,i)=>`<div class="lc2 rv"><div class="bg">${bld(i+2)}</div><div><h3>${l}</h3><p>${LDESC[l]}</p><button class="ln" data-go="${l}">Explore Properties →</button></div></div>`).join("");
$('loc').onclick=e=>{const b=e.target.closest('[data-go]');if(b){fl=b.dataset.go;$('fs').value=fl;draw();$('properties').scrollIntoView()}};
$('gk').onclick=()=>{fl="Ghatkopar";$('fs').value=fl;draw();$('properties').scrollIntoView()};
["Pant Nagar","Rajawadi","Vikhroli East","Vikhroli West","Kanjurmarg","Powai","Mulund"].forEach(s=>$('sec').insertAdjacentHTML('beforeend',`<span>${s}</span>`));
$('wy').innerHTML=[["eye","Local Market Understanding","Strong local focus with a broader service reach across Mumbai."],["sh","Transparent Communication","Clear and straightforward communication throughout the property journey."],["us","Personalized Consultation","Property guidance based on individual requirements."],["hs","Dedicated Assistance","Support during enquiries, property discussions and site visits."],["hd","Relationship-Focused Service","Focused on building long-term professional relationships through trust and responsible service."]].map(w=>`<div class="rv"><div class="ic">${ic(w[0])}</div><h3 style="font-size:18px;margin-bottom:6px">${w[1]}</h3><p style="color:var(--mu);font-size:15px">${w[2]}</p></div>`).join("");
$('st').innerHTML=[["Tell Us Your Requirement","Share your location, property type, budget and requirements."],["Explore Suitable Opportunities","Discuss available or potential opportunities relevant to your requirement."],["Visit & Discuss","Arrange property visits and discuss the relevant details."],["Move Forward","Receive assistance with discussions and the next steps."]].map((s,i)=>`<div class="stp rv"><div class="num">0${i+1}</div><h3>${s[0]}</h3><p style="color:var(--mu);font-size:15px">${s[1]}</p></div>`).join("");
if(SHOW_TESTIMONIALS)$('tm').innerHTML=TEST.map(t=>`<div class="tc rv"><p>"${t[2]}"</p><b>${t[0]}</b><div style="color:var(--mu);font-size:13px">${t[1]}</div></div>`).join("");else $('testimonials').remove();
$('l').innerHTML=[...LOCS,"Other"].map(l=>`<option>${l}</option>`).join("");
$('f').onsubmit=e=>{e.preventDefault();const v=id=>$(id).value||"-";window.open(wa(`Hello B.H Akhade Real Estate, I would like to make an enquiry.\nName: ${v('n')}\nMobile: ${v('p')}\nEmail: ${v('e')}\nEnquiry type: ${v('q')}\nLocation: ${v('l')}\nBudget: ${v('b')}\nProperty type: ${v('t')}\nMessage: ${v('m')}`),"_blank")};
const so=[["INSTAGRAM_URL","ig","Instagram"],["FACEBOOK_URL","fb","Facebook"],["LINKEDIN_URL","li","LinkedIn"]].filter(s=>SOCIAL[s[0]]);$('soc').innerHTML=so.map(s=>`<a href="${SOCIAL[s[0]]}" target="_blank" rel="noopener" aria-label="${s[2]}">${ic(s[1])}</a>`).join("");
if(IMG.hero)document.querySelector('.hero').style.background=`linear-gradient(rgba(18,38,58,.75),rgba(18,38,58,.9)),url(${IMG.hero}) center/cover`;

$('cr').innerHTML=DOCS.length?DOCS.map((d,i)=>`<div class="sv rv"><div class="ic">${ic('sh')}</div><h3>${d.title}</h3><p>${d.issuer}</p><button class="ln" data-c="${i}">View Certificate →</button></div>`).join(""):`<div class="sv" style="grid-column:1/-1"><div class="ic">${ic('sh')}</div><h3>Clarity Before You Commit</h3><p>Have a question about our process, the documentation involved or how a property transaction works? Ask us directly and we will walk you through it.</p><a class="ln" data-wa="Hello B.H Akhade Real Estate, I have a question about the process and documentation.">Ask a Question →</a></div>`;
$('cr').onclick=e=>{const b=e.target.closest('[data-c]');if(!b)return;const d=DOCS[b.dataset.c];last=b;$('mc').innerHTML=`<button class="x" id="cx" aria-label="Close">×</button><img src="${d.img}" alt="${d.title}" style="grid-column:1/-1;width:100%">`;md.classList.add('on');$('cx').focus();$('cx').onclick=cl};
draw();icons();link();
const nav=$('nav'),sc=()=>nav.classList.toggle('s',scrollY>40);sc();addEventListener('scroll',sc,{passive:true});
$('mb').onclick=()=>{const o=$('lk').classList.toggle('on');$('mb').setAttribute('aria-expanded',o)};$('lk').onclick=()=>$('lk').classList.remove('on');
const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('v');io.unobserve(x.target)}}),{threshold:.1});document.querySelectorAll('.rv').forEach(e=>io.observe(e));